### ISSUE TITLE
La touche début marche une première fois, pas une seconde

### ISSUE THREAD

**Issue by Herondil** [OliveLeb/virtual-keyboard#4]
Dès que je tape une autre lettre après avoir utilisé "Debut", le curseur repart automatiquement à la fin.

**Comment by OliveLeb** [comment]
Debut remet le curseur en début de ligne et Page up au tout début. C'est moi ça fonctionne bien hormis le fait que si on y insère un caractère, le curseur retourne à la fin. Est-ce le même problème?

**Comment by Herondil** [comment]
Oui !

**Comment by OliveLeb** [comment]
corrigé ainsi que #3  et #5 
bb8b64d8b86925b84f2699c17dc68858672fdd31
